---
# PKM Chatbot Embedding Pipeline Configuration

# Database Configuration
database:
  tracking_db_path: "data/tracking.db"
  vector_db:
    provider: "pinecone"
    api_key: "${PINECONE_API_KEY}"
    environment: "${PINECONE_ENVIRONMENT}"
    index_name: "${PINECONE_INDEX_NAME}"

# Embedding Configuration
embedding:
  # Model type: "e5" (primary) or "distiluse" (fallback)
  model_type: "e5"

  # Primary embedding model (E5)
  primary_model: "intfloat/multilingual-e5-large-instruct"

  # Fallback embedding model (DistilUSE)
  fallback_model: "sentence-transformers/distiluse-base-multilingual-cased-v2"

  # Hardware optimization
  device: "mps" # "mps" for M2 Max, "cuda" for NVIDIA GPUs, "cpu" for CPU

  # Title-enhanced embedding settings
  enable_title_enhanced: true
  title_weight: 0.3 # Weight applied to title embeddings (0-1)

# Processing Configuration
processing:
  # Supported file extensions
  supported_extensions: [".md", ".markdown"]

  # Files or directories to exclude
  exclude_patterns: ["node_modules", ".git", "venv"]

# Chunking Configuration
chunking:
  # Chunking settings
  max_chunk_size: 1024
  chunk_overlap: 100
  respect_structure: true
  preserve_code_blocks: true
  preserve_lists: true
  preserve_tables: true

# Metadata Configuration
metadata:
  extract_tags: true
  extract_links: true
  extract_keywords: false

# Pipeline Configuration
pipeline:
  # Worker settings
  max_workers: 4
  auto_scale: true

  # Processing mode
  # "auto" will decide based on file count, "bulk" or "incremental" for explicit mode
  processing_mode: "auto"
  bulk_threshold: 20 # Number of files that triggers bulk mode

  # Batch settings
  batch_size: 10

# Logging Configuration
logging:
  level: "INFO"
  log_file: "data/pipeline.log"
  console_output: true
