---
# PKM Chatbot Embedding Pipeline Configuration

# Database Configuration
database:
  tracking_db_path: data/document_tracker.db
  checkpoint_dir: data/checkpoints
  vector_db:
    provider: "pinecone"
    api_key: "${PINECONE_API_KEY}"
    environment: "${PINECONE_ENVIRONMENT}"
    index_name: "${PINECONE_INDEX_NAME}"
    dimension: 1536
    max_retries: 3
    retry_delay: 2.0
    batch_size: 100
    # Serverless configuration (optional)
    serverless: false
    cloud_provider: "aws" # aws, gcp, azure
    region: "us-west-2" # Region for serverless deployment

# Embedding Configuration
embedding:
  # Model type: "e5" (primary) or "distiluse" (fallback)
  model_type: e5

  # Primary embedding model (E5)
  primary_model: intfloat/multilingual-e5-small

  # Fallback embedding model (DistilUSE)
  fallback_model: sentence-transformers/distiluse-base-multilingual-cased-v1

  # Hardware optimization
  device: auto # can be cpu, cuda, mps, or auto

  # Title-enhanced embedding settings
  enable_title_enhanced: true
  title_weight: 0.3

# Processing Configuration
processing:
  # Supported file extensions
  include_patterns:
    - "*.md"
  exclude_patterns:
    - "node_modules"
    - ".git"
  title_patterns:
    - "title:"
    - "# "

# Chunking Configuration
chunking:
  # Chunking settings
  chunk_size: 256
  chunk_overlap: 32
  respect_structure: true
  preserve_code_blocks: true
  preserve_lists: true
  preserve_tables: true

# Metadata Configuration
metadata:
  extract_tags: true
  extract_links: true
  extract_keywords: false

# Pipeline Configuration
pipeline:
  # Mode can be one of: incremental, bulk, auto
  processing_mode: auto
  # Maximum number of workers to use
  max_workers: 4
  # Minimum number of files per worker before scaling up
  min_files_per_worker: 10
  # Enable/disable adaptive scaling based on system load
  enable_adaptive_scaling: true
  # Target CPU usage percentage for adaptive scaling (0-100)
  target_cpu_usage: 70
  # Memory threshold percentage for scaling back (0-100)
  memory_threshold: 90

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_file: "data/pipeline.log"
  console_output: true
