---
# PKM Chatbot Embedding Pipeline Test Configuration

# Database Configuration
database:
  tracking_db_path: data/test_document_tracker.db
  checkpoint_dir: data/test_checkpoints
  vector_db:
    provider: "pinecone"
    api_key: "${PINECONE_API_KEY}"
    environment: "${PINECONE_ENVIRONMENT}"
    index_name: "${PINECONE_INDEX_NAME}"
    dimension: 1536
    max_retries: 3
    retry_delay: 2.0
    batch_size: 100
    # Use test namespace to avoid affecting production data
    namespace: "test_namespace"
    # Serverless configuration (optional)
    serverless: false
    cloud_provider: "aws"
    region: "us-east-1"

# Embedding Configuration
embedding:
  # Use same model type as production
  model_type: e5

  # Primary embedding model (same as production)
  primary_model: intfloat/multilingual-e5-small

  # Fallback embedding model (same as production)
  fallback_model: sentence-transformers/distiluse-base-multilingual-cased-v1

  # Hardware optimization
  device: auto # Same as production

  # Title-enhanced embedding settings
  enable_title_enhanced: true
  title_weight: 0.3

# Processing Configuration
processing:
  # Supported file extensions
  include_patterns:
    - "*.md"
  exclude_patterns:
    - "node_modules"
    - ".git"
  title_patterns:
    - "title:"
    - "# "

# Chunking Configuration (same as production)
chunking:
  chunk_size: 256
  chunk_overlap: 32
  respect_structure: true
  preserve_code_blocks: true
  preserve_lists: true
  preserve_tables: true

# Metadata Configuration
metadata:
  extract_tags: true
  extract_links: true
  extract_keywords: false

# Pipeline Configuration (still using single worker for test stability)
pipeline:
  processing_mode: incremental
  max_workers: 1 # Using 1 worker for test stability (vs 4 in production)
  min_files_per_worker: 10
  enable_adaptive_scaling: false
  target_cpu_usage: 70
  memory_threshold: 90

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_file: "data/test_pipeline.log"
  console_output: true
